version: "3.9"

services:
  nlp-fastapi:
    build: .
    container_name: nlp-fastapi
    restart: always
    runtime: nvidia
    env_file:
      - .env # ✅ 명시적으로 .env 파일 로드
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
